# Generated by Django 3.0.3 on 2020-12-12 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20201212_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'get_latest_by': 'date', 'ordering': ['-date']},
        ),
    ]
