# Generated by Django 3.0.3 on 2021-10-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greensource_pages', '0001_initial'),
    ]

    operations = [
    ]
