# Generated by Django 3.0.3 on 2021-08-21 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greensource_pages', '0002_projects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
