# Generated by Django 3.0.3 on 2021-08-21 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greensource_pages', '0004_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.RemoveField(
            model_name='galllery',
            name='description',
        ),
        migrations.RemoveField(
            model_name='galllery',
            name='heading_id',
        ),
        migrations.RemoveField(
            model_name='galllery',
            name='second_image',
        ),
        migrations.RemoveField(
            model_name='galllery',
            name='title',
        ),
    ]
