# Generated by Django 3.0.3 on 2022-03-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greensource_pages', '0004_auto_20220328_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured',
            name='slug',
            field=models.SlugField(default=111, unique=True),
            preserve_default=False,
        ),
    ]
