# Generated by Django 3.0.3 on 2022-03-28 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greensource_pages', '0005_featured_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featured',
            name='slug',
        ),
    ]
