# Generated by Django 3.0.3 on 2022-08-11 10:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greensource_pages', '0006_remove_featured_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solar',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
