# Generated by Django 3.0.3 on 2021-08-30 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greensource_pages', '0006_galllery_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='galllery',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galllery_details',
            name='galllery',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='greensource_pages.Galllery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galllery_details',
            name='slug',
            field=models.SlugField(default=' ', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='galllery_details',
            name='content',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='galllery_details',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='galllery_details',
            name='tags',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='galllery_details',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
