# Generated by Django 3.0.3 on 2021-08-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greensource_pages', '0007_auto_20210830_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='galllery',
            name='title',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
