# Generated by Django 3.0.3 on 2022-10-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greensource_pages', '0007_auto_20220812_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('pics', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'ordering': ['-date'],
                'get_latest_by': 'date',
            },
        ),
    ]
