# Generated by Django 3.0.3 on 2021-08-30 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greensource_pages', '0008_galllery_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galllery',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='galllery',
            name='title',
        ),
        migrations.RemoveField(
            model_name='galllery_details',
            name='slug',
        ),
    ]
