# Generated by Django 3.0.3 on 2022-10-20 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greensource_pages', '0008_orderpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderPage',
        ),
    ]
