# Generated by Django 3.0.3 on 2021-08-30 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greensource_pages', '0009_auto_20210830_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galllery_details',
            name='galllery',
        ),
    ]
