# Generated by Django 3.0.3 on 2021-08-30 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greensource_pages', '0010_remove_galllery_details_galllery'),
    ]

    operations = [
        migrations.AddField(
            model_name='galllery_details',
            name='galllery',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='greensource_pages.Galllery'),
            preserve_default=False,
        ),
    ]
