# Generated by Django 3.0.3 on 2022-10-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greensource_pages', '0011_auto_20221024_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='pics',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
