# Generated by Django 3.0.3 on 2021-08-30 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greensource_pages', '0011_galllery_details_galllery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galllery_details',
            name='galllery',
        ),
    ]
