# Generated by Django 3.0.3 on 2022-10-24 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greensource_pages', '0012_landingpage_pics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='pics',
        ),
    ]
