# Generated by Django 3.0.3 on 2021-08-30 23:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('greensource_pages', '0012_remove_galllery_details_galllery'),
    ]

    operations = [
        migrations.AddField(
            model_name='galllery',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galllery_details',
            name='galllery',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='greensource_pages.Galllery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galllery_details',
            name='slug',
            field=models.SlugField(default=' ', unique=True),
            preserve_default=False,
        ),
    ]
