# Generated by Django 3.0.3 on 2021-08-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greensource_pages', '0013_auto_20210831_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galllery',
            name='image',
        ),
        migrations.AlterField(
            model_name='galllery',
            name='slug',
            field=models.SlugField(),
        ),
    ]
