# Generated by Django 3.0.3 on 2021-08-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greensource_pages', '0014_auto_20210831_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='galllery',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
