# Generated by Django 3.0.3 on 2022-10-26 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greensource_pages', '0014_landingpage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='title',
        ),
    ]
