# Generated by Django 3.0.3 on 2023-07-06 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greensource_pages', '0015_remove_landingpage_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Featured',
        ),
    ]
