# Generated by Django 3.0.3 on 2021-08-31 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greensource_pages', '0018_auto_20210831_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galllery',
            name='slug',
        ),
    ]
