# Generated by Django 3.0.3 on 2021-08-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greensource_pages', '0020_auto_20210831_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galllery',
            name='tag',
        ),
        migrations.AlterField(
            model_name='galllery',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
