# Generated by Django 3.0.3 on 2021-08-31 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greensource_pages', '0023_auto_20210831_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galllery',
            name='body',
        ),
        migrations.RemoveField(
            model_name='galllery',
            name='content',
        ),
        migrations.RemoveField(
            model_name='galllery',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='galllery',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='galllery',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='galllery',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='galllery',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='galllery',
            name='name',
        ),
        migrations.RemoveField(
            model_name='galllery',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='galllery',
            name='tags',
        ),
    ]
