# Generated by Django 3.0.3 on 2021-08-31 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greensource_pages', '0025_auto_20210831_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galllery',
            name='slug',
        ),
    ]
