# Generated by Django 3.0.3 on 2021-08-31 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greensource_pages', '0026_remove_galllery_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galllery',
            options={},
        ),
        migrations.RemoveField(
            model_name='galllery',
            name='body',
        ),
        migrations.RemoveField(
            model_name='galllery',
            name='content',
        ),
        migrations.RemoveField(
            model_name='galllery',
            name='date',
        ),
        migrations.RemoveField(
            model_name='galllery',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='galllery',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='galllery',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='galllery',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='galllery',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='galllery',
            name='name',
        ),
        migrations.RemoveField(
            model_name='galllery',
            name='tags',
        ),
        migrations.CreateModel(
            name='Galllery_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=100)),
                ('image1', models.ImageField(blank=True, upload_to='')),
                ('image2', models.ImageField(blank=True, upload_to='')),
                ('image3', models.ImageField(blank=True, upload_to='')),
                ('image4', models.ImageField(blank=True, upload_to='')),
                ('image5', models.ImageField(blank=True, upload_to='')),
                ('body', models.TextField()),
                ('galllery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greensource_pages.Galllery')),
            ],
            options={
                'ordering': ['-date'],
                'get_latest_by': 'date',
            },
        ),
    ]
