# Generated by Django 3.0.3 on 2021-08-31 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greensource_pages', '0027_auto_20210831_1821'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Galllery_details',
            new_name='Galllery_portfolio',
        ),
    ]
