# Generated by Django 3.0.3 on 2021-08-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greensource_pages', '0028_auto_20210831_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='galllery',
            name='date',
            field=models.DateField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
    ]
