# Generated by Django 3.0.3 on 2021-08-31 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greensource_pages', '0029_galllery_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galllery',
            options={'get_latest_by': 'date', 'ordering': ['-date']},
        ),
        migrations.DeleteModel(
            name='Galllery_portfolio',
        ),
    ]
