# Generated by Django 3.0.3 on 2021-09-11 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greensource_pages', '0032_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
