# Generated by Django 3.0.3 on 2021-09-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greensource_pages', '0032_portfolio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='Promotion',
        ),
    ]
