# Generated by Django 3.0.3 on 2021-09-11 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greensource_pages', '0033_auto_20210911_1507'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
