# Generated by Django 3.0.3 on 2021-09-19 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greensource_pages', '0035_auto_20210919_2035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Galllery',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
